version: '3.7'

services:
  
  web-app:
    container_name: web-app
    restart: always
    build: .
    ports:
    - 8080:80
    networks:
      - internal

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /usr/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - internal

networks:
  internal:
    driver: bridge
